import { FC, PropsWithChildren, CSSProperties } from 'react';
import Head from "next/head";
import { Navbar } from "../Navbar";



const style: CSSProperties = {
    padding: '0 2rem'
}



const MainLayout : FC <PropsWithChildren>= ({children}) => {
    return (
        <div  style={style} >
          <Head>
            <title> about next</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar/>
            <main className={'main'}>
              {children}
          </main>
        </div>
      )
}

export default MainLayout